---
- name: Ejecutar script de Python
  hosts: all
  tasks:
    - name: Copiar script de Python al servidor
      copy:
        src: /home/automation/cp_script.py
        dest: /home/ubuntu/cp_script.py
    - name: Ejecutar script de Python
      command: python3 /home/ubuntu/cp_script.py
