- hosts: all
  become: yes
  tasks:
    - name: Parar contenedores y eliminarlos
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        - portainer
        - watchtower
        - wordpress
        - db

    - name: Eliminar Docker Compose
      apt:
        name: docker-compose
        state: absent

    - name: Eliminar Docker
      apt:
        name: docker.io
        state: absent

    - name: Eliminar volumenes de Docker
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/docker/volumes/portainer_data
        - /var/lib/docker/volumes/wordpress
        - /var/lib/docker/volumes/db